import { IItem } from "./items.types";

export const itemsSeed: IItem[] = [
  {
    domain: "media",
    title: "The Expanse",
    type: "Series",
    status: "watching",
    value: 7,
    total: 24,
    unit: "eps",
    epMinute: 18,
    epDuration: 58,
    rating: 5,
    year: 2015,
    subtitle: "S3 · E7",
    genres: ["Sci-Fi", "Drama"],
    synopsis:
      "A hardened detective and a rogue ship's crew unravel a conspiracy that threatens the solar system.",
    notes: "Read the books first: the show diverges around S4.",
    cover: "",
  },
  {
    domain: "media",
    title: "Severance",
    type: "Series",
    status: "watching",
    value: 4,
    total: 9,
    unit: "eps",
    epMinute: 12,
    epDuration: 50,
    rating: 4,
    year: 2022,
    subtitle: "S1 · E4",
    genres: ["Sci-Fi", "Thriller"],
    synopsis: "Office workers surgically divide their work and personal memories.",
    notes: "",
    cover: "",
  },
  {
    domain: "media",
    title: "Blade Runner 2049",
    type: "Film",
    status: "completed",
    value: 164,
    total: 164,
    unit: "min",
    epMinute: 0,
    epDuration: 0,
    rating: 5,
    year: 2017,
    subtitle: "2h 44m",
    genres: ["Sci-Fi"],
    synopsis: "A young blade runner uncovers a secret that could plunge society into chaos.",
    notes: "Denis Villeneuve at his best.",
    cover: "",
  },
  {
    domain: "media",
    title: "Foundation",
    type: "Series",
    status: "backlog",
    value: 0,
    total: 0,
    unit: "eps",
    epMinute: 0,
    epDuration: 0,
    rating: 0,
    year: 2021,
    subtitle: "Queued",
    genres: ["Sci-Fi"],
    synopsis: "A band of exiles races to save humanity across a crumbling galactic empire.",
    notes: "",
    cover: "",
  },
  {
    domain: "media",
    title: "Darknet Diaries",
    type: "Podcast",
    status: "watching",
    value: 142,
    total: 0,
    unit: "eps",
    epMinute: 0,
    epDuration: 0,
    rating: 4,
    year: 2017,
    subtitle: "Ongoing",
    genres: ["True Crime", "Tech"],
    synopsis: "True stories from the dark side of the internet.",
    notes: "",
    cover: "",
  },
  {
    domain: "games",
    title: "Hollow Knight",
    status: "installed",
    gameType: "Native",
    platform: "PC",
    developer: "Team Cherry",
    publisher: "Team Cherry",
    year: 2017,
    genres: ["Metroidvania", "Action"],
    rating: 5,
    playtime: 47,
    lastPlayed: "2 days ago",
    installSize: 9,
    installDir: "D:\\Games\\HollowKnight",
    launcher: "D:\\Games\\HollowKnight\\hollow_knight.exe",
    icon: "",
    description: "A 2D action-adventure through a ruined insect kingdom.",
    notes: "",
    cover: "",
  },
  {
    domain: "games",
    title: "Chrono Trigger",
    status: "installed",
    gameType: "Emulated",
    platform: "SNES",
    developer: "Square",
    publisher: "Square",
    year: 1995,
    genres: ["JRPG", "Adventure"],
    rating: 5,
    playtime: 38,
    lastPlayed: "4 days ago",
    installSize: 1,
    installDir: "D:\\ROMs\\SNES",
    launcher:
      'D:\\Emulators\\RetroArch\\retroarch.exe -L snes9x "D:\\ROMs\\SNES\\ChronoTrigger.sfc"',
    icon: "",
    description: "A time-spanning JRPG masterpiece.",
    notes: "Run on the Snes9x core.",
    cover: "",
  },
  {
    domain: "games",
    title: "Celeste",
    status: "installed",
    gameType: "Native",
    platform: "PC",
    developer: "Maddy Makes Games",
    publisher: "Maddy Makes Games",
    year: 2018,
    genres: ["Platformer", "Indie"],
    rating: 5,
    playtime: 22,
    lastPlayed: "today",
    installSize: 2,
    installDir: "D:\\Games\\Celeste",
    launcher: "D:\\Games\\Celeste\\Celeste.exe",
    icon: "",
    description: "Climb a mountain and confront your inner self.",
    notes: "",
    cover: "",
  },
  {
    domain: "games",
    title: "The Witcher 3",
    status: "archived",
    gameType: "Native",
    platform: "PC",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    year: 2015,
    genres: ["RPG", "Adventure"],
    rating: 5,
    playtime: 120,
    lastPlayed: "3 months ago",
    installSize: 0,
    installDir: "",
    launcher: "",
    icon: "",
    description: "A monster hunter searches a war-torn world for his adopted daughter.",
    notes: "",
    cover: "",
  },
];
