import {
  Archive,
  Bookmark,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Cpu,
  Film,
  Folder,
  Gamepad2,
  HardDrive,
  Info,
  LayoutGrid,
  Layers,
  Mic,
  Monitor,
  Play,
  Settings,
  StickyNote,
  Terminal,
  TriangleAlert,
  Tv,
  Upload,
  X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const ICONS = {
  note: StickyNote,
  terminal: Terminal,
  folder: Folder,
  hardDrive: HardDrive,
  settings: Settings,
  upload: Upload,
  x: X,
  check: Check,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  triangleAlert: TriangleAlert,
  info: Info,
  grid: LayoutGrid,
  play: Play,
  bookmark: Bookmark,
  archive: Archive,
  gamepad: Gamepad2,
  tv: Tv,
  film: Film,
  mic: Mic,
  layers: Layers,
  monitor: Monitor,
  cpu: Cpu,
} satisfies Record<string, LucideIcon>;
